# Generated by Django 4.1.4 on 2022-12-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=30)),
                ('Steering_wheel', models.CharField(max_length=30)),
                ('Drive_unit', models.CharField(max_length=30)),
                ('Year', models.CharField(max_length=30)),
                ('Volume', models.CharField(max_length=30)),
                ('text', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
